profiles/urls.py
from django.contrib.auth.views import LoginView, PasswordChangeView, LogoutView
from django.urls import path

app_name = 'profiles'

urlpatterns = [
    path('login/', LoginView.as_view(), name='login'),
    path('password-change/', PasswordChangeView.as_view(), name='password-change'),
    path('logout/', LogoutView.as_view(), name='logout'),
]

water_levels/urls.py
from django.contrib.auth.views import LoginView, PasswordChangeView, LogoutView
from django.urls import path

from .views import *

app_name = 'water_levels'

urlpatterns = [
    path('', index, name='index'),
    path('graphs/', graphs, name='graphs'),
    path('upload_data/', upload_data, name='upload_data'),
]

water_maek/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('profiles.urls')),
    path('', include('water_levels.urls'))
]

templates/layouts/bs4_form.html
{% load widget_tweaks %}

{% for hidden_field in form.hidden_fields %}
  {{ hidden_field }}
{% endfor %}

{% if form.non_field_errors %}
  <div class="alert alert-danger" role="alert">
    {% for error in form.non_field_errors %}
      {{ error }}
    {% endfor %}
  </div>
{% endif %}

{% for field in form.visible_fields %}
  <div class="form-group">
    {{ field.label_tag }}

    {% if form.is_bound %}
      {% if field.errors %}
        {% render_field field class="form-control is-invalid" %}
        {% for error in field.errors %}
          <div class="invalid-feedback">
            {{ error }}
          </div>
        {% endfor %}
      {% else %}
        {% render_field field class="form-control is-valid" %}
      {% endif %}
    {% else %}
      {% render_field field class="form-control" %}
    {% endif %}

    {% if field.help_text %}
      <small class="form-text text-muted">{{ field.help_text }}</small>
    {% endif %}
  </div>
{% endfor %}

templates/layouts/nav.html
{% load static %}
<!-- Navigation -->
{#<div class="out-nav navbar-static-top">#}
{#  <ul>#}
{#    <li><img src="{% static '/journal/img/logo.png' %}"></li>#}
{#    <li class="{{ home_page }}"><a href="{% url 'subdivision:subdivision-list' %}">Главная</a></li>#}
{#    {% if request.user.is_authenticated %}#}
{#      <li class="{{ my_page }}"><a href="{% url 'subdivision:profile-subdivision' %}">Мой профиль</a></li>#}
{#      <li class="{{ my_page }}"><a href="http://srs.maek.kz/HB.html" target="_blank">Сегодня отмечают день рождения</a></li>#}
{#      <li class="{{ create_page }}"><a href="{% url 'journal:createjournalentry' %}">Заполнить журнал</a></li>#}
{#      <li><a href="{%static 'assets/outwork_instruction-2.pdf' %}#zoom=150" target="_blank">Инструкция пользователя</a></li>#}
{#    {% endif %}#}
{#    {% if request.user.is_authenticated %}#}
{#        <li style="float:right; padding-right: 20px;"><a href="{% url 'subdivision:logout' %}">Выйти</a></li>#}
{#        <li style="float:right; font-size: 16px;padding: 18px 10px; padding-right: 20px;">{{ request.user.username }}</li>#}
{#    {% endif %}#}
{#    {% if request.user.is_anonymous %}#}
{#    <li><a href="{%static 'assets/outwork_instruction-2.pdf' %}#zoom=150" target="_blank">Инструкция пользователя</a></li>#}
{#    <li style="float:right; padding-right: 20px;" ><a href="{% url 'subdivision:login' %}">Вход</a></li>#}
{#    {% endif %}#}
{#  </ul>#}
{#</div>#}
<nav class="navbar navbar-expand-lg bg-body-light out-nav navbar-static-top">
    <div class="container-fluid">
    <a class="navbar-brand" href="/"><img src="{% static '/journal/img/logo.png' %}"></a>
    <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarNav" aria-controls="navbarNav" aria-expanded="false" aria-label="Toggle navigation">
      <span class="navbar-toggler-icon"></span>
    </button>
    <div class="collapse navbar-collapse justify-content-between" id="navbarNav">
      <ul class="navbar-nav">
        <li class="{{ home_page }} nav-item">
          <a class="nav-link" href="{% url 'water_levels:index' %}">Главная</a>
        </li>
          <li class="{{ home_page }} nav-item">
          <a class="nav-link" href="{% url 'water_levels:graphs' %}">Графики</a>
        </li>
        <li class="{{ home_page }} nav-item">
          <a class="nav-link" href="{% url 'water_levels:upload_data' %}">Отправка данных</a>
        </li>
{#        <li class="nav-item {{ my_page }}">#}
{#          <a class="nav-link" href="{% url 'subdivision:profile-subdivision' %}">Мой профиль</a>#}
{#        </li>#}
{#        <li class="nav-item {{ my_page }}">#}
{#          <a class="nav-link"  href="http://srs.maek.kz/HB.html" target="_blank">Сегодня отмечают день рождения</a>#}
{#        </li>#}
{#          <li><a class="nav-link" href="{%static 'assets/outwork_instruction-2.pdf' %}#zoom=150" target="_blank">Инструкция пользователя</a></li>#}
      </ul>
        <ul class="navbar-nav">
            {% if request.user.is_authenticated %}
                <li><span>{{ request.user.username }}</span></li>
               <li><a href="{% url 'profiles:logout' %}">Выйти</a></li>
            {% elif request.user.is_anonymous %}
            <li><a href="{% url 'profiles:login' %}">Вход</a></li>
            {% endif %}
        </ul>

    </div>
    </div>
</nav>